use super::*;

/// Render a PipelineReport to a markdown string.
pub fn render_markdown(
    report: &PipelineReport,
    diff_text: Option<&str>,
    elapsed: Duration,
    settings: &Settings,
) -> String {
    // Paper-shaped surveys get title/authors/type headers; custom surveys
    // get a generic header.
    let meta = crate::models::paper_view(&report.orientation).map(|v| v.metadata);
    let mut md = String::new();

    // The report is the document; the reviewed paper is its subject. Keeping
    // those roles distinct avoids presenting the paper title/author block as
    // though it were authored by Pipeline.
    let subject = meta
        .as_ref()
        .map(|m| m.title.trim().to_string())
        .filter(|t| !t.is_empty())
        .unwrap_or_else(|| "Selected input".to_string());
    md.push_str("# Referee Report\n\n");

    let provider = capitalize(&settings.preferred_provider);
    let model = settings
        .model_selection(&settings.preferred_provider)
        .label();
    let effort = "default".to_string();

    let type_prefix = meta
        .as_ref()
        .map(|m| format!("**Type**: {} · ", m.paper_type))
        .unwrap_or_default();
    md.push_str(RUN_DETAILS_START);
    md.push('\n');
    md.push_str(&format!("**Review subject**: {subject}  \n"));
    if let Some(m) = &meta {
        if !m.authors.is_empty() {
            md.push_str(&format!("**Authors**: {}  \n", m.authors.join(", ")));
        }
    }
    md.push_str(&format!(
        "{}**Reviewed**: {} · `{}`  \n**LLM**: {} · **Model**: {} · **Effort**: {} · **Generated in**: {}  \n*Report generated by Pipeline*\n\n",
        type_prefix, report.report_date, report.paper_hash,
        provider, model, effort, format_duration(elapsed)
    ));
    md.push_str(RUN_DETAILS_END);
    md.push_str("\n\n");

    let quality_status = if report.quality.status.trim().is_empty() {
        if report.failed_steps.is_empty() {
            "done"
        } else {
            "partial"
        }
    } else {
        report.quality.status.as_str()
    };
    md.push_str(&format!(
        "> **Quality status:** {}. Coverage and limitations are reported below.\n\n",
        capitalize(quality_status)
    ));

    // Warning for failed steps
    if !report.failed_steps.is_empty() {
        let labels: Vec<&str> = report
            .failed_steps
            .iter()
            .map(|f| f.step_label.as_str())
            .collect();
        md.push_str(&format!(
            "> **Incomplete report.** The following steps failed and are not reflected below: {}.\n\n",
            labels.join(", ")
        ));
    }

    md.push_str("---\n\n");

    // Consolidated issues — use final_output() which handles both new and
    // legacy formats and never substitutes a parallel analysis for a failed
    // sequential report step.
    let final_text = crate::findings::canonical_findings(report)
        .filter(|findings| {
            !report.products.primary_step_id.is_empty()
                && findings
                    .source_step_id
                    .split('/')
                    .next()
                    .unwrap_or_default()
                    == report.products.primary_step_id
        })
        .map(|findings| crate::findings::render_markdown(&findings))
        .or_else(|| report.final_output().map(strip_to_report))
        .filter(|text| !text.trim().is_empty());
    if let Some(final_text) = final_text {
        md.push_str(&normalize_math_delimiters(&final_text));
        md.push_str("\n\n");
    } else {
        md.push_str("## Final report unavailable\n\n");
        if report.final_output_blocked_by_failed_sequential() {
            md.push_str(
                "The final report step did not return a valid report. Pipeline has not \n\
                 substituted an individual specialist analysis for the missing final report. \n\
                 Successful step outputs and rejected model responses remain preserved with \n\
                 the run for inspection.\n\n",
            );
        } else if report
            .all_outputs()
            .iter()
            .all(|output| output.skipped || output.raw_text.trim().is_empty())
        {
            md.push_str(
                "No completed step returned usable report content. Preserved run artifacts \n\
                 remain available for inspection.\n\n",
            );
        } else {
            md.push_str(
                "Pipeline could not identify usable canonical report content. Individual step \n\
                 outputs remain preserved with the run for inspection.\n\n",
            );
        }
    }

    // Revision diff
    if let Some(diff) = diff_text {
        md.push_str("---\n\n");
        md.push_str("## Revision Diff\n\n");
        md.push_str(&normalize_math_delimiters(&strip_to_report(diff)));
        md.push_str("\n\n");
    }

    render_quality_section(&mut md, report, quality_status);

    // Per-step timing / tokens / cost, when the run recorded any.
    if let Some(summary) = render_run_summary(report, settings) {
        md.push_str(RUN_DETAILS_START);
        md.push('\n');
        md.push_str("---\n\n");
        md.push_str(&summary);
        md.push_str(RUN_DETAILS_END);
        md.push_str("\n\n");
    }

    md.push_str("---\n");
    md
}

fn render_quality_section(md: &mut String, report: &PipelineReport, quality_status: &str) {
    let quality = &report.quality;
    md.push_str("---\n\n## Quality and limitations\n\n");
    md.push_str(&format!(
        "**Final status:** {}  \n",
        capitalize(quality_status)
    ));
    if quality.schema_version == 0 {
        md.push_str(
            "This report predates the deterministic quality ledger; only preserved failure metadata is available.\n\n",
        );
        return;
    }

    md.push_str(&format!(
        "**Extraction coverage:** {} input bytes via {}; {} pages, {} blocks, and {} assets recovered.  \n",
        quality.input_bytes,
        safe_inline(&quality.extraction_method),
        quality.recovered_pages,
        quality.recovered_blocks,
        quality.recovered_assets
    ));
    md.push_str(&format!(
        "**Orientation coverage:** {} bytes included; {} omitted.  \n",
        quality.orientation_included_bytes, quality.orientation_omitted_bytes
    ));
    md.push_str(&format!(
        "**Reviewer coverage:** {} completed, {} failed or blocked, {} skipped.  \n",
        quality.completed_steps.len(),
        quality.failed_steps.len(),
        quality.skipped_steps.len()
    ));
    md.push_str(&format!(
        "**Evidence:** {} verified, {} partially verified, {} unverified; {} manual-review item(s).  \n",
        quality.verified_evidence,
        quality.partially_verified_evidence,
        quality.unverified_evidence,
        quality.manual_review_items
    ));
    md.push_str(&format!(
        "**Schema retries:** {}.  \n",
        quality.schema_retry_events
    ));
    if !quality.requested_capabilities.is_empty() {
        md.push_str(&format!(
            "**Declared capabilities:** {}.  \n",
            safe_join(&quality.requested_capabilities)
        ));
    }
    if !quality.observed_capabilities.is_empty() {
        md.push_str(&format!(
            "**Observed tool classes:** {}.  \n",
            safe_join(&quality.observed_capabilities)
        ));
    }
    if !quality.external_providers.is_empty() {
        md.push_str(&format!(
            "**External providers:** {}.  \n",
            safe_join(&quality.external_providers)
        ));
    }
    md.push_str(&format!(
        "**Reproducibility hash:** `{}`\n\n",
        safe_inline(&quality.reproducibility_hash)
    ));

    if quality.limitations.is_empty() {
        md.push_str("No deterministic limitations were recorded.\n\n");
    } else {
        md.push_str("### Recorded limitations\n\n");
        for limitation in &quality.limitations {
            md.push_str(&format!("- {}\n", safe_inline(limitation)));
        }
        md.push('\n');
    }
}

fn safe_inline(value: &str) -> String {
    value
        .replace(['\r', '\n'], " ")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "\\|")
}

fn safe_join(values: &[String]) -> String {
    values
        .iter()
        .map(|value| safe_inline(value))
        .collect::<Vec<_>>()
        .join(", ")
}

pub(crate) fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => {
            let upper: String = first.to_uppercase().collect();
            let rest: String = chars.collect();
            upper + &rest
        }
    }
}
