import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import ExportControls from "./ExportControls";
import { detectReportIssues } from "../lib/issues";
import { renderSurvey } from "../lib/surveyMarkdown";
import {
  isPaperOrientation,
  type PipelineReport,
  type RunSummary,
} from "../lib/types";

const ArtifactExplorer = lazy(() => import("./ArtifactExplorer"));
const IssuesTable = lazy(() => import("./IssuesTable"));
const ReportViewer = lazy(() => import("./ReportViewer"));

interface ArtifactContent {
  text: string | null;
}

interface Props {
  runId?: string | null;
  markdown?: string;
  report?: PipelineReport | null;
  extractedText?: string;
  summary?: RunSummary | null;
  durationSecs?: number | null;
  onBack?: () => void;
}

type WorkspaceTab = "report" | "issues" | "sources";
type OutputView = "clean" | "raw";

const TAB_IDS: Record<WorkspaceTab, string> = {
  report: "report-workspace-tab-report",
  issues: "report-workspace-tab-issues",
  sources: "report-workspace-tab-sources",
};

const TAB_PANEL_IDS: Record<WorkspaceTab, string> = {
  report: "report-workspace-panel-report",
  issues: "report-workspace-panel-issues",
  sources: "report-workspace-panel-sources",
};

function formatDuration(seconds?: number | null) {
  if (!seconds || seconds <= 0 || !Number.isFinite(seconds)) return "—";
  const roundedSeconds = Math.round(seconds);
  const minutes = Math.floor(roundedSeconds / 60);
  const remainder = roundedSeconds % 60;
  return minutes ? `${minutes}m ${remainder}s` : `${remainder}s`;
}

function formatDate(value?: string | null) {
  if (!value) return "—";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function reportTitle(report: PipelineReport | null, summary?: RunSummary | null) {
  if (summary?.title) return summary.title;
  if (report && isPaperOrientation(report.orientation)) {
    const title = report.orientation.metadata?.title;
    if (title) return title;
  }
  if (summary?.input_name) return summary.input_name;
  return "Pipeline report";
}

function resolvedProvider(report: PipelineReport | null, summary?: RunSummary | null) {
  if (summary?.provider) return summary.provider;
  const providers = Array.from(new Set(
    report?.step_outputs
      .flatMap((step) => [step.provider, ...(step.calls ?? []).map((call) => call.provider)])
      .filter((value): value is string => Boolean(value)) ?? [],
  ));
  return providers.join(", ") || "Default";
}

function resolvedModel(report: PipelineReport | null) {
  const models = Array.from(new Set(
    report?.step_outputs
      .flatMap((step) => [step.model, ...(step.calls ?? []).map((call) => call.model)])
      .filter((value): value is string => Boolean(value)) ?? [],
  ));
  if (models.length === 0) return "Automatic";
  if (models.length <= 2) return models.join(", ");
  return `${models[0]} +${models.length - 1}`;
}

export function splitUnexpectedPreamble(markdown: string) {
  let clean = markdown
    .replace(
      /<!-- PIPELINE RUN DETAILS START -->[\s\S]*?<!-- PIPELINE RUN DETAILS END -->\s*/g,
      "",
    )
    .trim();
  const narration: string[] = [];

  const firstHeading = clean.search(/^#\s+\S/m);
  if (firstHeading > 0) {
    narration.push(clean.slice(0, firstHeading).trim());
    clean = clean.slice(firstHeading).trimStart();
  }

  // Older reports predate the run-details markers. Their generated metadata
  // sits between the H1 and the first rule; the workspace now presents these
  // values as structured provenance instead.
  const legacyHeader = clean.match(/^(#\s+[^\n]+\n)([\s\S]*?)(^---\s*$)/m);
  if (
    legacyHeader &&
    /Report generated by Pipeline|\*\*(?:LLM|Reviewed|Model|Type)\*\*/i.test(legacyHeader[2])
  ) {
    clean = clean.replace(legacyHeader[0], `${legacyHeader[1]}\n${legacyHeader[3]}`);
  }

  // Some older model outputs placed tool-use narration after the generated
  // header and immediately before the first H2, occasionally on the same
  // line as that heading.
  const firstSection = clean.indexOf("## ");
  if (firstSection > 0) {
    const beforeSection = clean.slice(0, firstSection);
    const lastRule = beforeSection.lastIndexOf("---");
    if (lastRule >= 0) {
      const candidate = beforeSection.slice(lastRule + 3).trim();
      if (
        candidate &&
        /^(?:I(?:'|’| a| wi|’m|’ll)|Here(?:'|’)s|Let me|The prompt\b)/i.test(candidate)
      ) {
        narration.push(candidate);
        clean = `${beforeSection.slice(0, lastRule + 3).trimEnd()}\n\n${clean.slice(firstSection)}`;
      }
    }
  }

  // Run telemetry remains available in the raw report artifact under Sources;
  // keep the primary reading view focused on the substantive report.
  clean = clean.replace(
    /\n+(?:---\s*\n+)?## Run summary\b[\s\S]*$/i,
    "",
  );

  return {
    clean: clean.trim(),
    preamble: narration.filter(Boolean).join("\n\n"),
  };
}

function TabButton({
  active,
  count,
  id,
  label,
  onClick,
  onKeyDown,
  panelId,
}: {
  active: boolean;
  count?: number;
  id: string;
  label: string;
  onClick: () => void;
  onKeyDown: (event: React.KeyboardEvent<HTMLButtonElement>) => void;
  panelId: string;
}) {
  return (
    <button
      id={id}
      type="button"
      role="tab"
      aria-controls={panelId}
      aria-selected={active}
      tabIndex={active ? 0 : -1}
      onClick={onClick}
      onKeyDown={onKeyDown}
      className={`relative h-11 px-1 text-sm font-medium transition-colors focus-visible:outline-none
                  focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-gray-400 ${
                    active
                      ? "text-gray-950 dark:text-gray-50"
                      : "text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200"
                  }`}
    >
      {label}
      {count !== undefined && (
        <span className="ml-1.5 text-xs tabular-nums text-gray-500 dark:text-gray-400">
          {count}
        </span>
      )}
      {active && (
        <span className="absolute inset-x-0 bottom-0 h-0.5 rounded-full bg-gray-950 dark:bg-gray-100" />
      )}
    </button>
  );
}

function ProvenanceCard({
  report,
  runId,
  summary,
  durationSecs,
}: {
  report: PipelineReport;
  runId?: string | null;
  summary?: RunSummary | null;
  durationSecs?: number | null;
}) {
  const fields = [
    [
      "Authors",
      report && isPaperOrientation(report.orientation)
        ? report.orientation.metadata.authors.join(", ") || "—"
        : "—",
    ],
    ["Workflow", summary?.profile_name || summary?.profile_id || "Current workflow"],
    ["Provider", resolvedProvider(report, summary)],
    ["Model", resolvedModel(report)],
    ["Duration", formatDuration(summary?.duration_secs || durationSecs)],
    ["Completed", formatDate(summary?.created || report.report_date)],
    ["Run", runId ? runId.slice(0, 18) : report.paper_hash?.slice(0, 12) || "Unsaved"],
  ];

  return (
    <section
      aria-label="Run provenance"
      className="mx-auto mt-6 w-[min(52rem,calc(100%-3rem))] rounded-xl border border-gray-200/80
                 bg-gray-50/70 px-4 py-3 dark:border-gray-800 dark:bg-gray-900/55"
    >
      <div className="mb-2 flex items-center gap-2">
        <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
        <h2 className="text-xs font-semibold uppercase tracking-[0.12em] text-gray-500 dark:text-gray-400">
          Run provenance
        </h2>
      </div>
      <dl className="grid grid-cols-2 gap-x-6 gap-y-2 sm:grid-cols-3">
        {fields.map(([label, value]) => (
          <div key={label} className="min-w-0">
            <dt className="text-[11px] text-gray-500 dark:text-gray-400">{label}</dt>
            <dd className="truncate text-xs font-medium text-gray-700 dark:text-gray-300" title={value}>
              {value}
            </dd>
          </div>
        ))}
      </dl>
    </section>
  );
}

function LocalSources({
  extractedText,
  report,
}: {
  extractedText: string;
  report: PipelineReport;
}) {
  const options = [
    { id: "extracted", label: "Extracted text", markdown: extractedText },
    { id: "orientation", label: "Orientation map", markdown: renderSurvey(report.orientation) },
    ...report.step_outputs.map((step) => ({
      id: `step:${step.step_id}`,
      label: step.step_label,
      markdown: `# ${step.step_label}\n\n**Phase:** ${step.phase} · **Agent:** ${step.agent || "default"}\n\n---\n\n${step.raw_text}`,
    })),
  ];
  const [selected, setSelected] = useState(options[0]?.id ?? "");
  const active = options.find((option) => option.id === selected) ?? options[0];

  return (
    <div className="flex h-full min-h-0">
      <nav className="w-56 shrink-0 border-r border-gray-200 p-3 dark:border-gray-800">
        <p className="mb-2 px-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-gray-500 dark:text-gray-400">
          Sources
        </p>
        {options.map((option) => (
          <button
            key={option.id}
            type="button"
            onClick={() => setSelected(option.id)}
            className={`mb-0.5 w-full truncate rounded-lg px-2.5 py-1.5 text-left text-xs ${
              option.id === active?.id
                ? "bg-gray-900 text-white dark:bg-gray-100 dark:text-gray-900"
                : "text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
            }`}
          >
            {option.label}
          </button>
        ))}
      </nav>
      <div className="min-w-0 flex-1">
        {active && <ReportViewer markdown={active.markdown} />}
      </div>
    </div>
  );
}

export default function ReportWorkspace({
  runId,
  markdown: initialMarkdown = "",
  report: initialReport = null,
  extractedText,
  summary,
  durationSecs,
  onBack,
}: Props) {
  const [tab, setTab] = useState<WorkspaceTab>("report");
  const [report, setReport] = useState<PipelineReport | null>(initialReport);
  const [markdown, setMarkdown] = useState(initialMarkdown);
  const [loading, setLoading] = useState(Boolean(runId && (!initialReport || !initialMarkdown)));
  const [error, setError] = useState<string | null>(null);
  const [outputView, setOutputView] = useState<OutputView>("clean");

  useEffect(() => {
    setReport(initialReport);
    setMarkdown(initialMarkdown);
    setTab("report");
    setOutputView("clean");
    if (!runId || (initialReport && initialMarkdown)) {
      setLoading(false);
      setError(null);
      return;
    }

    let live = true;
    setLoading(true);
    Promise.all([
      invoke<PipelineReport>("get_run_report", { runId }),
      invoke<ArtifactContent>("read_artifact", { runId, relPath: "report.md" }),
    ])
      .then(([loadedReport, artifact]) => {
        if (!live) return;
        setReport(loadedReport);
        setMarkdown(artifact.text ?? "");
        setError(null);
      })
      .catch((caught) => {
        if (live) setError(caught instanceof Error ? caught.message : String(caught));
      })
      .finally(() => {
        if (live) setLoading(false);
      });
    return () => {
      live = false;
    };
  }, [initialMarkdown, initialReport, runId]);

  const issues = useMemo(
    () => (report ? detectReportIssues(report) : null),
    [report],
  );
  const presentation = useMemo(() => splitUnexpectedPreamble(markdown), [markdown]);
  const visibleMarkdown = outputView === "clean" ? presentation.clean : markdown;
  const title = reportTitle(report, summary);
  const status = summary?.status || (report?.failed_steps?.length ? "partial" : "done");
  const availableTabs: WorkspaceTab[] = issues && issues.length > 0
    ? ["report", "issues", "sources"]
    : ["report", "sources"];
  const handleTabKeyDown = (
    event: React.KeyboardEvent<HTMLButtonElement>,
    currentTab: WorkspaceTab,
  ) => {
    const currentIndex = availableTabs.indexOf(currentTab);
    let nextIndex: number | null = null;
    if (event.key === "ArrowRight") {
      nextIndex = (currentIndex + 1) % availableTabs.length;
    } else if (event.key === "ArrowLeft") {
      nextIndex = (currentIndex - 1 + availableTabs.length) % availableTabs.length;
    } else if (event.key === "Home") {
      nextIndex = 0;
    } else if (event.key === "End") {
      nextIndex = availableTabs.length - 1;
    }
    if (nextIndex === null) return;
    event.preventDefault();
    const nextTab = availableTabs[nextIndex];
    setTab(nextTab);
    document.getElementById(TAB_IDS[nextTab])?.focus();
  };

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center text-sm text-gray-500 dark:text-gray-400">
        Loading report…
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="flex h-full items-center justify-center p-8">
        <div role="alert" className="max-w-md rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/40 dark:text-red-300">
          <p className="font-medium">Could not open this report.</p>
          <p className="mt-1 text-xs">{error || "The structured report is unavailable."}</p>
          {onBack && (
            <button type="button" onClick={onBack} className="mt-3 font-medium underline">
              Back to history
            </button>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-full min-h-0 flex-col bg-white dark:bg-gray-950">
      <header className="shrink-0 border-b border-gray-200/80 bg-white px-6 pb-4 pt-5 dark:border-gray-800 dark:bg-gray-950">
        <div className="flex min-w-0 items-start gap-4">
          {onBack && (
            <button
              type="button"
              onClick={onBack}
              aria-label="Back to history"
              className="mt-0.5 rounded-lg p-1.5 text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-800
                         focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-100"
            >
              <svg aria-hidden="true" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
                <path strokeLinecap="round" strokeLinejoin="round" d="m15 18-6-6 6-6" />
              </svg>
            </button>
          )}
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2">
              <span className={`h-1.5 w-1.5 rounded-full ${
                status === "done" ? "bg-emerald-500" : status === "partial" ? "bg-amber-500" : "bg-red-500"
              }`} />
              <span className="text-[11px] font-semibold uppercase tracking-[0.12em] text-gray-500 dark:text-gray-400">
                {status === "done" ? "Completed report" : `${status} report`}
              </span>
            </div>
            <h1 className="mt-1 truncate text-xl font-semibold tracking-[-0.02em] text-gray-950 dark:text-gray-50" title={title}>
              {title}
            </h1>
            <p className="mt-1 truncate text-xs text-gray-500 dark:text-gray-400">
              {summary?.profile_name || "Current workflow"}
              <span className="mx-1.5 text-gray-300 dark:text-gray-700">·</span>
              {resolvedProvider(report, summary)}
              <span className="mx-1.5 text-gray-300 dark:text-gray-700">·</span>
              {resolvedModel(report)}
              <span className="mx-1.5 text-gray-300 dark:text-gray-700">·</span>
              {formatDuration(summary?.duration_secs || durationSecs)}
            </p>
          </div>
          <ExportControls
            runId={runId}
            markdown={markdown}
            report={report}
            extractedText={extractedText}
          />
        </div>
      </header>

      {report.failed_steps && report.failed_steps.length > 0 && (
        <div className="shrink-0 border-b border-amber-200 bg-amber-50 px-6 py-2 text-xs text-amber-800 dark:border-amber-900 dark:bg-amber-950/35 dark:text-amber-300">
          <span className="font-semibold">Incomplete report.</span>{" "}
          {report.failed_steps.map((failure) => failure.step_label).join(", ")} did not complete.
        </div>
      )}

      <div
        role="tablist"
        aria-label="Report workspace"
        className="flex h-11 shrink-0 items-center gap-6 border-b border-gray-200 bg-white px-6 dark:border-gray-800 dark:bg-gray-950"
      >
        <TabButton
          active={tab === "report"}
          id={TAB_IDS.report}
          label="Report"
          panelId={TAB_PANEL_IDS.report}
          onClick={() => setTab("report")}
          onKeyDown={(event) => handleTabKeyDown(event, "report")}
        />
        {issues && issues.length > 0 && (
          <TabButton
            active={tab === "issues"}
            count={issues.length}
            id={TAB_IDS.issues}
            label="Issues"
            panelId={TAB_PANEL_IDS.issues}
            onClick={() => setTab("issues")}
            onKeyDown={(event) => handleTabKeyDown(event, "issues")}
          />
        )}
        <TabButton
          active={tab === "sources"}
          id={TAB_IDS.sources}
          label="Sources"
          panelId={TAB_PANEL_IDS.sources}
          onClick={() => setTab("sources")}
          onKeyDown={(event) => handleTabKeyDown(event, "sources")}
        />
      </div>

      <div className="min-h-0 flex-1">
        <Suspense
          fallback={(
            <div className="flex h-full items-center justify-center text-sm text-gray-500 dark:text-gray-400">
              Loading workspace…
            </div>
          )}
        >
          {tab === "issues" && issues ? (
            <div
              id={TAB_PANEL_IDS.issues}
              role="tabpanel"
              aria-labelledby={TAB_IDS.issues}
              className="h-full overflow-auto"
            >
              <IssuesTable issues={issues} runId={runId ?? null} />
            </div>
          ) : tab === "sources" ? (
            <div
              id={TAB_PANEL_IDS.sources}
              role="tabpanel"
              aria-labelledby={TAB_IDS.sources}
              className="h-full"
            >
              {runId ? (
                <ArtifactExplorer
                  runId={runId}
                  fallbackMarkdown={markdown}
                  deferInitialArtifact
                />
              ) : (
                <LocalSources extractedText={extractedText ?? ""} report={report} />
              )}
            </div>
          ) : (
            <div
              id={TAB_PANEL_IDS.report}
              role="tabpanel"
              aria-labelledby={TAB_IDS.report}
              className="h-full overflow-hidden"
            >
              <div className="flex h-full min-h-0 flex-col">
                {presentation.preamble && (
                  <div
                    role="status"
                    className="flex shrink-0 items-center gap-3 border-b border-amber-200 bg-amber-50/80 px-6 py-2
                               text-xs text-amber-800 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-300"
                  >
                    <span className="font-semibold">Output-quality warning</span>
                    <span className="min-w-0 flex-1 truncate">
                      Model narration was hidden in Clean view.
                    </span>
                    <div className="flex rounded-md border border-amber-300/80 p-0.5 dark:border-amber-800">
                      {(["clean", "raw"] as OutputView[]).map((view) => (
                        <button
                          key={view}
                          type="button"
                          onClick={() => setOutputView(view)}
                          className={`rounded px-2 py-0.5 text-[11px] font-medium ${
                            outputView === view
                              ? "bg-amber-900 text-white dark:bg-amber-200 dark:text-amber-950"
                              : "hover:bg-amber-100 dark:hover:bg-amber-900/50"
                          }`}
                        >
                          {view === "clean" ? "Clean view" : "Raw output"}
                        </button>
                      ))}
                    </div>
                  </div>
                )}
                <div className="min-h-0 flex-1 overflow-hidden">
                  <div className="flex h-full min-h-0 flex-col">
                    <ProvenanceCard
                      report={report}
                      runId={runId}
                      summary={summary}
                      durationSecs={durationSecs}
                    />
                    <div className="min-h-0 flex-1">
                      <ReportViewer markdown={visibleMarkdown} />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
        </Suspense>
      </div>
    </div>
  );
}
