import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import ExportControls from "./ExportControls";
import { detectReportIssues, type IssueEvidence } from "../lib/issues";
import { renderSurvey } from "../lib/surveyMarkdown";
import {
  buildRunProvenance,
  formatRunDate,
  formatRunDuration,
  formatTokens,
  provenanceMarkdown as renderProvenanceMarkdown,
  type RunProvenance,
} from "../lib/runProvenance";
import {
  isPaperOrientation,
  type PipelineReport,
  type RunSummary,
} from "../lib/types";
import type {
  ArtifactContent as ExplorerArtifactContent,
  ArtifactExplorerPreload,
  ArtifactSelectionRequest,
  ArtifactSelectionTarget,
  RunManifest,
} from "./ArtifactExplorer";

const loadArtifactExplorer = () => import("./ArtifactExplorer");
const ArtifactExplorer = lazy(loadArtifactExplorer);
const IssuesTable = lazy(() => import("./IssuesTable"));
const ReportViewer = lazy(() => import("./ReportViewer"));

interface ArtifactContent {
  text: string | null;
}

interface Props {
  runId?: string | null;
  markdown?: string;
  report?: PipelineReport | null;
  extractedText?: string;
  summary?: RunSummary | null;
  durationSecs?: number | null;
  onBack?: () => void;
  /** Open a cited page or artifact when navigating here from a project ledger. */
  initialSourceSelection?: ArtifactSelectionTarget | null;
}

type WorkspaceTab = "report" | "provenance" | "issues" | "sources";
type OutputView = "clean" | "raw";
type CanonicalReportProblem =
  | "failed-final-step"
  | "missing-content"
  | "no-step-output"
  | "apparent-refusal";

const APPARENT_REFUSAL_RE = /\bi(?:\s+(?:cannot|can't|am\s+unable\s+to|must\s+refuse\s+to|will\s+not|won't)|'m\s+unable\s+to)\s+(?:comply(?:\s+with\s+(?:this|the)\s+request)?|(?:provide|produce|write|generate|complete)\s+(?:(?:this|the|a)\s+)?(?:requested\s+)?(?:report|review|task|request)|(?:help|assist)\s+with\s+(?:this|that|the\s+request)|follow\s+(?:these|the)\s+instructions)\b/i;

const TAB_IDS: Record<WorkspaceTab, string> = {
  report: "report-workspace-tab-report",
  provenance: "report-workspace-tab-provenance",
  issues: "report-workspace-tab-issues",
  sources: "report-workspace-tab-sources",
};

const TAB_PANEL_IDS: Record<WorkspaceTab, string> = {
  report: "report-workspace-panel-report",
  provenance: "report-workspace-panel-provenance",
  issues: "report-workspace-panel-issues",
  sources: "report-workspace-panel-sources",
};

function reportTitle(report: PipelineReport | null, summary?: RunSummary | null) {
  if (summary?.title) return summary.title;
  if (report && isPaperOrientation(report.orientation)) {
    const title = report.orientation.metadata?.title;
    if (title) return title;
  }
  if (summary?.input_name) return summary.input_name;
  return "Pipeline report";
}

export function splitUnexpectedPreamble(markdown: string, paperTitle = "") {
  let clean = markdown
    .replace(
      /<!-- PIPELINE RUN DETAILS START -->[\s\S]*?<!-- PIPELINE RUN DETAILS END -->\s*/g,
      "",
    )
    .trim();
  const narration: string[] = [];

  const firstHeading = clean.search(/^#\s+\S/m);
  if (firstHeading > 0) {
    narration.push(clean.slice(0, firstHeading).trim());
    clean = clean.slice(firstHeading).trimStart();
  }

  // Older reports predate the run-details markers. Their generated metadata
  // sits between the H1 and the first rule; the workspace now presents these
  // values as structured provenance instead.
  const legacyHeader = clean.match(/^(#\s+[^\n]+\n)([\s\S]*?)(^---\s*$)/m);
  if (
    legacyHeader &&
    /Report generated by Pipeline|\*\*(?:LLM|Reviewed|Model|Type)\*\*/i.test(legacyHeader[2])
  ) {
    clean = clean.replace(legacyHeader[0], `${legacyHeader[1]}\n${legacyHeader[3]}`);
  }

  // Some older model outputs placed tool-use narration after the generated
  // header and immediately before the first H2, occasionally on the same
  // line as that heading.
  const firstSection = clean.indexOf("## ");
  if (firstSection > 0) {
    const beforeSection = clean.slice(0, firstSection);
    const lastRule = beforeSection.lastIndexOf("---");
    if (lastRule >= 0) {
      const candidate = beforeSection.slice(lastRule + 3).trim();
      if (
        candidate &&
        /^(?:I(?:'|’| a| wi|’m|’ll)|Here(?:'|’)s|Let me|The prompt\b)/i.test(candidate)
      ) {
        narration.push(candidate);
        clean = `${beforeSection.slice(0, lastRule + 3).trimEnd()}\n\n${clean.slice(firstSection)}`;
      }
    }
  }

  // Run telemetry remains available in the raw report artifact under Sources;
  // keep the primary reading view focused on the substantive report.
  clean = clean.replace(
    /\n+(?:---\s*\n+)?## Run summary\b[\s\S]*$/i,
    "",
  );

  // The app header already identifies the paper. Older report artifacts used
  // the paper title and authors as a second document masthead; replace that
  // duplicate identity with the kind of document the reader is opening.
  const firstTitle = clean.match(/^#\s+([^\n]+)\n?/);
  if (
    firstTitle &&
    paperTitle.trim() &&
    firstTitle[1].replace(/[*_`]/g, "").trim() === paperTitle.trim()
  ) {
    clean = clean.replace(firstTitle[0], "# Referee Report\n");
    clean = clean.replace(
      /^(# Referee Report)\s*\n(?:\s*\n)*(?:\*\*Authors\*\*:[^\n]*(?:\n|$))?/i,
      "$1\n\n",
    );
    clean = clean.replace(/^(# Referee Report)\n{3,}/, "$1\n\n");
  }

  return {
    clean: clean.trim(),
    preamble: narration.filter(Boolean).join("\n\n"),
  };
}

/** Remove the in-app document label when the PDF has its own masthead. */
export function reportBodyForPdf(markdown: string): string {
  return markdown
    .replace(/^#\s+(?:Referee|Review|Pipeline)?\s*Report\s*\n+/i, "")
    .replace(/^---\s*\n+/, "")
    .trim();
}

/**
 * Keep the reading surface conservative at the last boundary. The backend
 * rejects these cases for new runs; this also protects old or partially
 * recovered artifacts that predate the report contract.
 */
export function canonicalReportProblem(
  report: PipelineReport | null,
  markdown: string,
): CanonicalReportProblem | null {
  const visible = markdown.trim();
  if (!visible) return "missing-content";

  if (visible.length <= 4_000) {
    const prefix = visible.slice(0, 1_200).replace(/[’‘]/g, "'");
    if (APPARENT_REFUSAL_RE.test(prefix)) return "apparent-refusal";
  }

  if (!report) return null;
  const usableOutputs = (report.step_outputs ?? []).filter(
    (output) => !output.skipped && output.raw_text.trim().length > 0,
  );
  const hasSequentialOutput = usableOutputs.some(
    (output) => output.phase === "sequential",
  );
  const hasFailedFinalStep = (report.failed_steps ?? []).some((failure) => {
    if (failure.phase === "sequential") return true;
    if (failure.phase) return false;
    // Old reports did not persist phase. Restrict the compatibility heuristic
    // to conventional final-step names rather than guessing from every error.
    return /\b(?:synthesi[sz]|consolidat|editor|validat)\w*\b/i.test(
      `${failure.step_id} ${failure.step_label}`,
    );
  });
  if (!hasSequentialOutput && hasFailedFinalStep) return "failed-final-step";
  if (usableOutputs.length === 0) return "no-step-output";
  return null;
}

function canonicalProblemMessage(problem: CanonicalReportProblem): string {
  switch (problem) {
    case "failed-final-step":
      return "The final report step did not return usable content. Pipeline did not substitute an individual agent analysis for the missing final report.";
    case "apparent-refusal":
      return "The model returned an apparent refusal instead of report content. The response was preserved for inspection but is not presented as a completed report.";
    case "no-step-output":
      return "No completed step returned usable report content. Any captured attempts remain available for inspection.";
    case "missing-content":
      return "The canonical report artifact is empty or unavailable. Other run artifacts may still contain useful diagnostic material.";
  }
}

function TabButton({
  active,
  count,
  id,
  label,
  onClick,
  onKeyDown,
  panelId,
}: {
  active: boolean;
  count?: number;
  id: string;
  label: string;
  onClick: () => void;
  onKeyDown: (event: React.KeyboardEvent<HTMLButtonElement>) => void;
  panelId: string;
}) {
  return (
    <button
      id={id}
      type="button"
      role="tab"
      aria-controls={panelId}
      aria-selected={active}
      tabIndex={active ? 0 : -1}
      onClick={onClick}
      onKeyDown={onKeyDown}
      className={`relative h-11 px-1 text-sm font-medium transition-colors focus-visible:outline-none
                  focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-gray-400 ${
                    active
                      ? "text-gray-950 dark:text-gray-50"
                      : "text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200"
                  }`}
    >
      {label}
      {count !== undefined && (
        <span className="ml-1.5 text-xs tabular-nums text-gray-500 dark:text-gray-400">
          {count}
        </span>
      )}
      {active && (
        <span className="absolute inset-x-0 bottom-0 h-0.5 rounded-full bg-gray-950 dark:bg-gray-100" />
      )}
    </button>
  );
}

function ProvenancePanel({ provenance }: { provenance: RunProvenance }) {
  const fields = [
    ["Review subject", provenance.subject],
    ["Authors", provenance.authors.join(", ") || "—"],
    ["Workflow", provenance.workflow],
    ["Completed", formatRunDate(provenance.completed)],
    ["Duration", formatRunDuration(provenance.duration_secs)],
    ["Report", provenance.run_id || "Unsaved"],
    ["Provider", provenance.provider_summary],
    ["Model", provenance.model_summary],
  ];
  const showCacheWrite = provenance.totals.cache_write_input_tokens > 0;

  return (
    <div className="h-full overflow-y-auto">
      <section aria-label="Report provenance" className="mx-auto max-w-5xl px-8 py-10">
        <div className="flex items-start justify-between gap-6">
          <div>
            <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-gray-500 dark:text-gray-400">
              Completed report
            </p>
            <h2 className="mt-1 text-2xl font-semibold tracking-[-0.025em] text-gray-950 dark:text-gray-50">
              Report provenance
            </h2>
            <p className="mt-2 max-w-2xl text-sm text-gray-600 dark:text-gray-300">
              Reproducibility details and provider-reported token accounting for this report.
            </p>
          </div>
          <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${
            provenance.status === "done"
              ? "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300"
              : "bg-amber-50 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300"
          }`}>
            {provenance.status === "done" ? "Completed" : provenance.status}
          </span>
        </div>

        <dl className="mt-8 grid gap-px overflow-hidden rounded-xl border border-gray-200 bg-gray-200 sm:grid-cols-2 lg:grid-cols-4 dark:border-gray-800 dark:bg-gray-800">
          {fields.map(([label, value]) => (
            <div key={label} className="min-w-0 bg-white px-4 py-3.5 dark:bg-gray-950">
              <dt className="text-[11px] font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">
                {label}
              </dt>
              <dd className="mt-1 break-words text-sm font-medium text-gray-800 dark:text-gray-200" title={value}>
                {value}
              </dd>
            </div>
          ))}
        </dl>

        <div className="mt-10">
          <div className="flex flex-wrap items-end justify-between gap-3">
            <div>
              <h3 className="text-base font-semibold text-gray-950 dark:text-gray-50">Token usage</h3>
              <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                Cached input is a subset of logical input, as reported by each provider.
              </p>
            </div>
            <div className="flex gap-5 text-right">
              {[
                ["Input", provenance.totals.input_tokens],
                ["Output", provenance.totals.output_tokens],
                ["Cached", provenance.totals.cached_input_tokens],
              ].map(([label, value]) => (
                <div key={label}>
                  <p className="text-[10px] font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">{label}</p>
                  <p className="text-sm font-semibold tabular-nums text-gray-900 dark:text-gray-100">
                    {formatTokens(value as number)}
                  </p>
                </div>
              ))}
            </div>
          </div>

          <div className="mt-4 overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-800">
            <table className="w-full min-w-[52rem] border-collapse text-left text-sm">
              <thead className="bg-gray-50 text-[11px] uppercase tracking-wide text-gray-500 dark:bg-gray-900 dark:text-gray-400">
                <tr>
                  <th className="px-4 py-2.5 font-medium">Step</th>
                  <th className="px-4 py-2.5 font-medium">Provider</th>
                  <th className="px-4 py-2.5 font-medium">Model</th>
                  <th className="px-4 py-2.5 text-right font-medium">Input</th>
                  <th className="px-4 py-2.5 text-right font-medium">Output</th>
                  <th className="px-4 py-2.5 text-right font-medium">Cached</th>
                  {showCacheWrite && <th className="px-4 py-2.5 text-right font-medium">Cache write</th>}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 dark:divide-gray-800">
                {provenance.step_usage.length ? provenance.step_usage.map((row) => (
                  <tr key={`${row.step_id}:${row.provider}:${row.model}`}>
                    <td className="px-4 py-3 font-medium text-gray-800 dark:text-gray-200" title={row.step_id}>
                      {row.step_label}
                    </td>
                    <td className="px-4 py-3 font-medium text-gray-800 dark:text-gray-200">
                      {row.provider}
                      {row.transports.length > 0 && (
                        <span className="ml-2 text-[10px] font-semibold text-gray-400">
                          {row.transports.join(" + ")}
                        </span>
                      )}
                    </td>
                    <td className="px-4 py-3 text-gray-600 dark:text-gray-300">{row.model}</td>
                    <td className="px-4 py-3 text-right tabular-nums text-gray-600 dark:text-gray-300">{formatTokens(row.input_tokens)}</td>
                    <td className="px-4 py-3 text-right tabular-nums text-gray-600 dark:text-gray-300">{formatTokens(row.output_tokens)}</td>
                    <td className="px-4 py-3 text-right tabular-nums text-gray-600 dark:text-gray-300">{formatTokens(row.cached_input_tokens)}</td>
                    {showCacheWrite && (
                      <td className="px-4 py-3 text-right tabular-nums text-gray-600 dark:text-gray-300">{formatTokens(row.cache_write_input_tokens)}</td>
                    )}
                  </tr>
                )) : (
                  <tr>
                    <td colSpan={showCacheWrite ? 7 : 6} className="px-4 py-5 text-center text-gray-500 dark:text-gray-400">
                      This provider did not report token usage.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
          {!provenance.usage_matches_total && (
            <p className="mt-3 text-xs text-gray-500 dark:text-gray-400">
              Report totals may also include extraction, orientation, setup calls, or reused step provenance that is not attributable to one saved provider/model row.
            </p>
          )}
        </div>
      </section>
    </div>
  );
}

function LocalSources({
  extractedText,
  report,
}: {
  extractedText: string;
  report: PipelineReport;
}) {
  const options = [
    { id: "extracted", label: "Extracted text", markdown: extractedText },
    { id: "orientation", label: "Orientation map", markdown: renderSurvey(report.orientation) },
    ...report.step_outputs.map((step) => ({
      id: `step:${step.step_id}`,
      label: step.step_label,
      markdown: `# ${step.step_label}\n\n**Phase:** ${step.phase} · **Agent:** ${step.agent || "default"}\n\n---\n\n${step.raw_text}`,
    })),
  ];
  const [selected, setSelected] = useState(options[0]?.id ?? "");
  const active = options.find((option) => option.id === selected) ?? options[0];

  return (
    <div className="flex h-full min-h-0">
      <nav className="w-56 shrink-0 border-r border-gray-200 p-3 dark:border-gray-800">
        <p className="mb-2 px-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-gray-500 dark:text-gray-400">
          Sources
        </p>
        {options.map((option) => (
          <button
            key={option.id}
            type="button"
            onClick={() => setSelected(option.id)}
            className={`mb-0.5 w-full truncate rounded-lg px-2.5 py-1.5 text-left text-xs ${
              option.id === active?.id
                ? "bg-gray-900 text-white dark:bg-gray-100 dark:text-gray-900"
                : "text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
            }`}
          >
            {option.label}
          </button>
        ))}
      </nav>
      <div className="min-w-0 flex-1">
        {active && <ReportViewer markdown={active.markdown} />}
      </div>
    </div>
  );
}

export default function ReportWorkspace({
  runId,
  markdown: initialMarkdown = "",
  report: initialReport = null,
  extractedText,
  summary,
  durationSecs,
  onBack,
  initialSourceSelection = null,
}: Props) {
  const [tab, setTab] = useState<WorkspaceTab>(initialSourceSelection ? "sources" : "report");
  const [report, setReport] = useState<PipelineReport | null>(initialReport);
  const [markdown, setMarkdown] = useState(initialMarkdown);
  const [loading, setLoading] = useState(Boolean(runId && (!initialReport || !initialMarkdown)));
  const [reportError, setReportError] = useState<string | null>(null);
  const [markdownError, setMarkdownError] = useState<string | null>(null);
  const [outputView, setOutputView] = useState<OutputView>("clean");
  const [artifactPreload, setArtifactPreload] = useState<ArtifactExplorerPreload | null>(null);
  const [runManifest, setRunManifest] = useState<RunManifest | null>(null);
  const [sourceRequest, setSourceRequest] = useState<ArtifactSelectionRequest | null>(
    initialSourceSelection ? { key: Date.now(), ...initialSourceSelection } : null,
  );

  useEffect(() => {
    setArtifactPreload(null);
    setRunManifest(null);
    setSourceRequest(initialSourceSelection
      ? { key: Date.now(), ...initialSourceSelection }
      : null);
    if (!runId) return;
    let live = true;

    // Sources are deliberately code-split and normally read artifacts only on
    // selection. Warm the viewer code, its small manifest, and the one large
    // text artifact readers commonly open first while they read the report.
    // The promises are passed through so opening Sources never repeats I/O.
    const manifest = invoke<RunManifest>("get_run_manifest", { runId });
    const readableDocument = invoke<ExplorerArtifactContent>("read_artifact", {
      runId,
      relPath: "context/document.md",
    });
    void loadArtifactExplorer().catch((caught) => {
      console.error("Failed to preload the artifact viewer:", caught);
    });
    // A missing historical artifact must not surface as an unhandled
    // background error. ArtifactExplorer retries normally if it is selected.
    void manifest
      .then((loaded) => {
        if (live) setRunManifest(loaded);
      })
      .catch(() => undefined);
    void readableDocument.catch(() => undefined);
    setArtifactPreload({ runId, manifest, readableDocument });
    return () => {
      live = false;
    };
  }, [initialSourceSelection, runId]);

  useEffect(() => {
    setReport(initialReport);
    setMarkdown(initialMarkdown);
    setTab(initialSourceSelection ? "sources" : "report");
    setOutputView("clean");
    setReportError(null);
    setMarkdownError(null);
    if (!runId || (initialReport && initialMarkdown)) {
      setLoading(false);
      return;
    }

    let live = true;
    setLoading(true);
    Promise.allSettled([
      initialReport
        ? Promise.resolve(initialReport)
        : invoke<PipelineReport>("get_run_report", { runId }),
      initialMarkdown
        ? Promise.resolve({ text: initialMarkdown } as ArtifactContent)
        : invoke<ArtifactContent>("read_artifact", { runId, relPath: "report.md" }),
    ])
      .then(([loadedReport, artifact]) => {
        if (!live) return;
        if (loadedReport.status === "fulfilled") {
          setReport(loadedReport.value);
          setReportError(null);
        } else {
          setReportError(
            loadedReport.reason instanceof Error
              ? loadedReport.reason.message
              : String(loadedReport.reason),
          );
        }
        if (artifact.status === "fulfilled") {
          setMarkdown(artifact.value.text ?? "");
          setMarkdownError(null);
        } else {
          setMarkdownError(
            artifact.reason instanceof Error
              ? artifact.reason.message
              : String(artifact.reason),
          );
          // The artifact explorer is independent of both canonical report
          // files, so make the recoverable material the default destination.
          setTab("sources");
        }
      })
      .finally(() => {
        if (live) setLoading(false);
      });
    return () => {
      live = false;
    };
  }, [initialMarkdown, initialReport, initialSourceSelection, runId]);

  const issues = useMemo(
    () => (report ? detectReportIssues(report) : null),
    [report],
  );
  const openEvidence = (evidence: IssueEvidence) => {
    if (!runId || (!evidence.page && !evidence.artifactPath)) return;
    setSourceRequest({
      key: Date.now(),
      page: evidence.page,
      relPath: evidence.artifactPath,
    });
    setTab("sources");
  };
  const paperTitle =
    report && isPaperOrientation(report.orientation)
      ? (report.orientation.metadata?.title ?? "")
      : "";
  const presentation = useMemo(
    () => splitUnexpectedPreamble(markdown, paperTitle),
    [markdown, paperTitle],
  );
  const visibleMarkdown = outputView === "clean" ? presentation.clean : markdown;
  const reportProblem = useMemo(
    () => canonicalReportProblem(report, presentation.clean),
    [presentation.clean, report],
  );
  const pdfMarkdown = useMemo(
    () => reportBodyForPdf(presentation.clean),
    [presentation.clean],
  );
  const provenance = useMemo(() => {
    if (!report) return null;
    const built = buildRunProvenance({
      report,
      summary,
      manifest: runManifest,
      runId,
      durationSecs,
    });
    return reportProblem && built.status === "done"
      ? { ...built, status: "partial" }
      : built;
  }, [durationSecs, report, reportProblem, runId, runManifest, summary]);
  const title = reportTitle(report, summary);
  const loadProblem = [reportError, markdownError].filter(Boolean).join(" · ");
  const reportedStatus = provenance?.status
    || runManifest?.status
    || (report?.failed_steps?.length || loadProblem ? "partial" : "done");
  const status = reportProblem && reportedStatus === "done"
    ? "partial"
    : reportedStatus;
  const availableTabs: WorkspaceTab[] = [
    "report",
    ...(provenance ? ["provenance" as const] : []),
    ...(issues && issues.length > 0 ? ["issues" as const] : []),
    "sources",
  ];
  const openAgentReports = () => {
    const first = runManifest?.artifacts.find(
      (artifact) => artifact.group === "agent_response",
    );
    if (first) {
      setSourceRequest({ key: Date.now(), relPath: first.rel_path });
    }
    setTab("sources");
  };
  const handleTabKeyDown = (
    event: React.KeyboardEvent<HTMLButtonElement>,
    currentTab: WorkspaceTab,
  ) => {
    const currentIndex = availableTabs.indexOf(currentTab);
    let nextIndex: number | null = null;
    if (event.key === "ArrowRight") {
      nextIndex = (currentIndex + 1) % availableTabs.length;
    } else if (event.key === "ArrowLeft") {
      nextIndex = (currentIndex - 1 + availableTabs.length) % availableTabs.length;
    } else if (event.key === "Home") {
      nextIndex = 0;
    } else if (event.key === "End") {
      nextIndex = availableTabs.length - 1;
    }
    if (nextIndex === null) return;
    event.preventDefault();
    const nextTab = availableTabs[nextIndex];
    setTab(nextTab);
    document.getElementById(TAB_IDS[nextTab])?.focus();
  };

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center text-sm text-gray-500 dark:text-gray-400">
        Loading report…
      </div>
    );
  }

  if (!runId && (!report || !provenance)) {
    return (
      <div className="flex h-full items-center justify-center p-8">
        <div role="alert" className="max-w-md rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/40 dark:text-red-300">
          <p className="font-medium">Could not open this report.</p>
          <p className="mt-1 text-xs">The structured report is unavailable.</p>
          {onBack && (
            <button type="button" onClick={onBack} className="mt-3 font-medium underline">
              Back to history
            </button>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-full min-h-0 flex-col bg-white dark:bg-gray-950">
      <header className="shrink-0 border-b border-gray-200/80 bg-white px-6 pb-4 pt-5 dark:border-gray-800 dark:bg-gray-950">
        <div className="flex min-w-0 items-start gap-4">
          {onBack && (
            <button
              type="button"
              onClick={onBack}
              aria-label="Back to history"
              className="mt-0.5 rounded-lg p-1.5 text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-800
                         focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-100"
            >
              <svg aria-hidden="true" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
                <path strokeLinecap="round" strokeLinejoin="round" d="m15 18-6-6 6-6" />
              </svg>
            </button>
          )}
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2">
              <span className={`h-1.5 w-1.5 rounded-full ${
                status === "done" ? "bg-emerald-500" : status === "partial" ? "bg-amber-500" : "bg-red-500"
              }`} />
              <span className="text-[11px] font-semibold uppercase tracking-[0.12em] text-gray-500 dark:text-gray-400">
                {status === "done" ? "Completed report" : `${status} report`}
              </span>
            </div>
            <h1 className="mt-1 truncate text-xl font-semibold tracking-[-0.02em] text-gray-950 dark:text-gray-50" title={title}>
              {title}
            </h1>
            <p className="mt-1 truncate text-xs text-gray-500 dark:text-gray-400">
              {provenance ? (
                <>
                  {provenance.workflow}
                  <span className="mx-1.5 text-gray-300 dark:text-gray-700">·</span>
                  <span title={provenance.provider_summary}>{provenance.provider_summary}</span>
                  <span className="mx-1.5 text-gray-300 dark:text-gray-700">·</span>
                  <span title={provenance.model_summary}>{provenance.model_summary}</span>
                  <span className="mx-1.5 text-gray-300 dark:text-gray-700">·</span>
                  {formatRunDuration(provenance.duration_secs)}
                </>
              ) : (
                "Canonical report metadata unavailable · preserved artifacts remain accessible"
              )}
            </p>
          </div>
          {report && provenance && (
            <ExportControls
              runId={runId}
              markdown={markdown}
              pdfMarkdown={pdfMarkdown}
              provenanceMarkdown={renderProvenanceMarkdown(provenance)}
              report={report}
              extractedText={extractedText}
            />
          )}
        </div>
      </header>

      {loadProblem && (
        <div className="flex shrink-0 items-center gap-3 border-b border-amber-200 bg-amber-50 px-6 py-2 text-xs text-amber-800 dark:border-amber-900 dark:bg-amber-950/35 dark:text-amber-300">
          <span className="min-w-0 flex-1 truncate">
            <span className="font-semibold">Canonical report is incomplete.</span>{" "}
            {loadProblem} Agent reports and other report artifacts remain available.
          </span>
          <button
            type="button"
            onClick={openAgentReports}
            className="shrink-0 rounded border border-amber-300 px-2 py-1 font-medium hover:bg-amber-100 dark:border-amber-800 dark:hover:bg-amber-900/40"
          >
            View agent reports
          </button>
        </div>
      )}

      {report?.failed_steps && report.failed_steps.length > 0 && (
        <div className="shrink-0 border-b border-amber-200 bg-amber-50 px-6 py-2 text-xs text-amber-800 dark:border-amber-900 dark:bg-amber-950/35 dark:text-amber-300">
          <span className="font-semibold">Incomplete report.</span>{" "}
          {report.failed_steps.map((failure) => failure.step_label).join(", ")} did not complete.
          {runId && (
            <button
              type="button"
              onClick={openAgentReports}
              className="ml-2 font-semibold underline underline-offset-2"
            >
              View agent reports
            </button>
          )}
        </div>
      )}

      <div
        role="tablist"
        aria-label="Report workspace"
        className="flex h-11 shrink-0 items-center gap-6 border-b border-gray-200 bg-white px-6 dark:border-gray-800 dark:bg-gray-950"
      >
        <TabButton
          active={tab === "report"}
          id={TAB_IDS.report}
          label="Report"
          panelId={TAB_PANEL_IDS.report}
          onClick={() => setTab("report")}
          onKeyDown={(event) => handleTabKeyDown(event, "report")}
        />
        {provenance && (
          <TabButton
            active={tab === "provenance"}
            id={TAB_IDS.provenance}
            label="Provenance"
            panelId={TAB_PANEL_IDS.provenance}
            onClick={() => setTab("provenance")}
            onKeyDown={(event) => handleTabKeyDown(event, "provenance")}
          />
        )}
        {issues && issues.length > 0 && (
          <TabButton
            active={tab === "issues"}
            count={issues.length}
            id={TAB_IDS.issues}
            label="Issues"
            panelId={TAB_PANEL_IDS.issues}
            onClick={() => setTab("issues")}
            onKeyDown={(event) => handleTabKeyDown(event, "issues")}
          />
        )}
        <TabButton
          active={tab === "sources"}
          id={TAB_IDS.sources}
          label="Sources"
          panelId={TAB_PANEL_IDS.sources}
          onClick={() => setTab("sources")}
          onKeyDown={(event) => handleTabKeyDown(event, "sources")}
        />
      </div>

      <div className="min-h-0 flex-1">
        <Suspense
          fallback={(
            <div className="flex h-full items-center justify-center text-sm text-gray-500 dark:text-gray-400">
              Loading workspace…
            </div>
          )}
        >
          {tab === "issues" && issues ? (
            <div
              id={TAB_PANEL_IDS.issues}
              role="tabpanel"
              aria-labelledby={TAB_IDS.issues}
              className="h-full overflow-auto"
            >
              <IssuesTable
                issues={issues}
                runId={runId ?? null}
                onOpenEvidence={runId ? openEvidence : undefined}
              />
            </div>
          ) : tab === "provenance" && provenance ? (
            <div
              id={TAB_PANEL_IDS.provenance}
              role="tabpanel"
              aria-labelledby={TAB_IDS.provenance}
              className="h-full"
            >
              <ProvenancePanel provenance={provenance} />
            </div>
          ) : tab === "sources" ? (
            <div
              id={TAB_PANEL_IDS.sources}
              role="tabpanel"
              aria-labelledby={TAB_IDS.sources}
              className="h-full"
            >
              {runId ? (
                <ArtifactExplorer
                  runId={runId}
                  fallbackMarkdown={markdown}
                  deferInitialArtifact
                  preload={artifactPreload}
                  selectionRequest={sourceRequest}
                />
              ) : report ? (
                <LocalSources extractedText={extractedText ?? ""} report={report} />
              ) : (
                <div className="flex h-full items-center justify-center p-8 text-sm text-gray-500 dark:text-gray-400">
                  No local source material is available.
                </div>
              )}
            </div>
          ) : (
            <div
              id={TAB_PANEL_IDS.report}
              role="tabpanel"
              aria-labelledby={TAB_IDS.report}
              className="h-full overflow-hidden"
            >
              <div className="flex h-full min-h-0 flex-col">
                {presentation.preamble && (
                  <div
                    role="status"
                    className="flex shrink-0 items-center gap-3 border-b border-amber-200 bg-amber-50/80 px-6 py-2
                               text-xs text-amber-800 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-300"
                  >
                    <span className="font-semibold">Output-quality warning</span>
                    <span className="min-w-0 flex-1 truncate">
                      Model narration was hidden in Clean view.
                    </span>
                    <div className="flex rounded-md border border-amber-300/80 p-0.5 dark:border-amber-800">
                      {(["clean", "raw"] as OutputView[]).map((view) => (
                        <button
                          key={view}
                          type="button"
                          onClick={() => setOutputView(view)}
                          className={`rounded px-2 py-0.5 text-[11px] font-medium ${
                            outputView === view
                              ? "bg-amber-900 text-white dark:bg-amber-200 dark:text-amber-950"
                              : "hover:bg-amber-100 dark:hover:bg-amber-900/50"
                          }`}
                        >
                          {view === "clean" ? "Clean view" : "Raw output"}
                        </button>
                      ))}
                    </div>
                  </div>
                )}
                <div className="min-h-0 flex-1 overflow-hidden">
                  {reportProblem ? (
                    <div className="flex h-full items-center justify-center p-8 text-center">
                      <div role="alert" className="max-w-lg">
                        <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-full bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300">
                          <svg aria-hidden="true" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v4m0 4h.01M10.3 3.6 2.6 17a2 2 0 0 0 1.7 3h15.4a2 2 0 0 0 1.7-3L13.7 3.6a2 2 0 0 0-3.4 0Z" />
                          </svg>
                        </div>
                        <p className="mt-3 font-medium text-gray-800 dark:text-gray-100">
                          No final report was produced.
                        </p>
                        <p className="mt-1 text-xs leading-relaxed text-gray-500 dark:text-gray-400">
                          {canonicalProblemMessage(reportProblem)}
                        </p>
                        <button
                          type="button"
                          onClick={openAgentReports}
                          className="mt-4 rounded border border-gray-300 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-100 dark:border-gray-700 dark:text-gray-200 dark:hover:bg-gray-800"
                        >
                          Inspect preserved outputs
                        </button>
                      </div>
                    </div>
                  ) : markdown.trim() ? (
                    <ReportViewer markdown={visibleMarkdown} />
                  ) : (
                    <div className="flex h-full items-center justify-center p-8 text-center text-sm text-gray-500 dark:text-gray-400">
                      <div>
                        <p className="font-medium text-gray-700 dark:text-gray-200">
                          The canonical rendered report is unavailable.
                        </p>
                        <p className="mt-1 max-w-md text-xs">
                          Open Agent reports to inspect every preserved model response, including rejected attempts.
                        </p>
                        {runId && (
                          <button
                            type="button"
                            onClick={openAgentReports}
                            className="mt-3 rounded border border-gray-300 px-3 py-1.5 text-xs font-medium hover:bg-gray-100 dark:border-gray-700 dark:hover:bg-gray-800"
                          >
                            View agent reports
                          </button>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}
        </Suspense>
      </div>
    </div>
  );
}
