version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /gui
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(npm)"
    groups:
      npm-runtime:
        dependency-type: production
      npm-build-and-test:
        dependency-type: development

  - package-ecosystem: cargo
    directory: /gui/src-tauri
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(cargo)"
    groups:
      rust:
        patterns:
          - "*"
