//! Report rendering.

use crate::models::PipelineReport;
use crate::settings::Settings;
use regex::Regex;
use std::sync::LazyLock;
use std::time::Duration;

static PREAMBLE_RE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?mi)^(I'(?:ve|ll|m)|I (?:have|need|can|should|will)|Let me|Now (?:I|let)|OK[,.]|Alright[,.]|Here (?:is|are)|Looking at|After reading|Having read)[^\n]*\n*"
    ).expect("preamble regex is invalid")
});

/// Extract content between `<!-- REPORT START -->` and `<!-- REPORT END -->` markers.
/// Falls back to the full text (with preamble stripping) if markers aren't present.
pub fn strip_to_report(text: &str) -> String {
    let trimmed = text.trim();

    const START: &str = "<!-- REPORT START -->";
    const END: &str = "<!-- REPORT END -->";

    if let Some(start_pos) = trimmed.find(START) {
        let content_start = start_pos + START.len();
        if let Some(end_pos) = trimmed[content_start..].find(END) {
            return trimmed[content_start..content_start + end_pos].trim().to_string();
        }
        // START found but no END — take everything after START
        return trimmed[content_start..].trim().to_string();
    }

    // No markers — fall back to preamble stripping
    strip_preamble(trimmed)
}

/// Strip LLM chain-of-thought preamble from output.
/// Removes lines like "I've now read the full paper. Let me compile..."
/// that appear before the actual content.
fn strip_preamble(text: &str) -> String {
    let trimmed = text.trim();

    // Only strip from the beginning — don't touch mid-text occurrences.
    // Guard against infinite loops (e.g., zero-width matches).
    let mut result = trimmed;
    for _ in 0..50 {
        let stripped = result.trim_start();
        if let Some(m) = PREAMBLE_RE.find(stripped) {
            if m.start() == 0 && m.end() > 0 {
                result = &stripped[m.end()..];
                continue;
            }
        }
        break;
    }

    result.trim().to_string()
}

fn format_duration(d: Duration) -> String {
    let total_secs = d.as_secs();
    let mins = total_secs / 60;
    let secs = total_secs % 60;
    if mins > 0 {
        format!("{mins}m {secs}s")
    } else {
        format!("{secs}s")
    }
}

/// Render a PipelineReport to a markdown string.
pub fn render_markdown(report: &PipelineReport, diff_text: Option<&str>, elapsed: Duration, settings: &Settings) -> String {
    // Paper-shaped surveys get title/authors/type headers; custom surveys
    // get a generic header.
    let meta = crate::models::paper_view(&report.orientation).map(|v| v.metadata);
    let mut md = String::new();

    // Title
    let title = meta
        .as_ref()
        .map(|m| m.title.trim().to_string())
        .filter(|t| !t.is_empty())
        .unwrap_or_else(|| "Report".to_string());
    md.push_str(&format!("# {title}\n\n"));

    // Metadata — single compact paragraph with line breaks
    if let Some(m) = &meta {
        if !m.authors.is_empty() {
            md.push_str(&format!("**Authors**: {}  \n", m.authors.join(", ")));
        }
    }

    let provider = capitalize(&settings.preferred_provider);
    let model = match settings.preferred_provider.as_str() {
        "codex" => if settings.codex_model.is_empty() { "default".to_string() } else { settings.codex_model.clone() },
        "gemini" => if settings.gemini_model.is_empty() { "default".to_string() } else { settings.gemini_model.clone() },
        _ => if settings.claude_model.is_empty() { "default".to_string() } else { settings.claude_model.clone() },
    };
    let effort = match settings.preferred_provider.as_str() {
        "codex" => if settings.codex_effort.is_empty() { "default".to_string() } else { settings.codex_effort.clone() },
        "gemini" => "n/a".to_string(),
        _ => if settings.claude_effort.is_empty() { "default".to_string() } else { settings.claude_effort.clone() },
    };

    let type_prefix = meta
        .as_ref()
        .map(|m| format!("**Type**: {} · ", m.paper_type))
        .unwrap_or_default();
    md.push_str(&format!(
        "{}**Reviewed**: {} · `{}`  \n**LLM**: {} · **Model**: {} · **Effort**: {} · **Generated in**: {}  \n*Report generated by Pipeline*\n\n",
        type_prefix, report.report_date, &report.paper_hash,
        provider, model, effort, format_duration(elapsed)
    ));

    // Warning for failed steps
    if !report.failed_steps.is_empty() {
        let labels: Vec<&str> = report.failed_steps.iter().map(|f| f.step_label.as_str()).collect();
        md.push_str(&format!(
            "> **Incomplete report.** The following steps failed and are not reflected below: {}.\n\n",
            labels.join(", ")
        ));
    }

    md.push_str("---\n\n");

    // Consolidated issues — use final_output() which handles both new and legacy formats
    if let Some(final_text) = report.final_output() {
        md.push_str(&strip_to_report(final_text));
        md.push_str("\n\n");
    }

    // Revision diff
    if let Some(diff) = diff_text {
        md.push_str("---\n\n");
        md.push_str("## Revision Diff\n\n");
        md.push_str(&strip_to_report(diff));
        md.push_str("\n\n");
    }

    md.push_str("---\n");
    md
}

pub(crate) fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => {
            let upper: String = first.to_uppercase().collect();
            let rest: String = chars.collect();
            upper + &rest
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── strip_to_report ────────────────────────────────────────────

    #[test]
    fn strip_to_report_extracts_between_markers() {
        let input = "preamble\n<!-- REPORT START -->\nActual report.\n<!-- REPORT END -->\ntrailing";
        assert_eq!(strip_to_report(input), "Actual report.");
    }

    #[test]
    fn strip_to_report_start_without_end() {
        let input = "<!-- REPORT START -->\nContent without end marker";
        assert_eq!(strip_to_report(input), "Content without end marker");
    }

    #[test]
    fn strip_to_report_no_markers_strips_preamble() {
        let input = "I've now read the full paper.\nActual content here.";
        assert_eq!(strip_to_report(input), "Actual content here.");
    }

    #[test]
    fn strip_to_report_no_markers_no_preamble() {
        let input = "## Issues\n\n1. First issue.";
        assert_eq!(strip_to_report(input), "## Issues\n\n1. First issue.");
    }

    #[test]
    fn strip_to_report_empty() {
        assert_eq!(strip_to_report(""), "");
        assert_eq!(strip_to_report("   "), "");
    }

    // ── strip_preamble ─────────────────────────────────────────────

    #[test]
    fn strip_preamble_removes_chain_of_thought() {
        let input = "Let me analyze this paper.\nI'll focus on methodology.\n## Real Content";
        assert_eq!(strip_preamble(input), "## Real Content");
    }

    #[test]
    fn strip_preamble_preserves_clean_text() {
        let input = "## Issues\n\n1. The regression specification...";
        assert_eq!(strip_preamble(input), input);
    }

    #[test]
    fn strip_preamble_empty() {
        assert_eq!(strip_preamble(""), "");
    }

    // ── format_duration ────────────────────────────────────────────

    #[test]
    fn format_duration_seconds_only() {
        assert_eq!(format_duration(Duration::from_secs(45)), "45s");
    }

    #[test]
    fn format_duration_minutes_and_seconds() {
        assert_eq!(format_duration(Duration::from_secs(125)), "2m 5s");
    }

    #[test]
    fn format_duration_zero() {
        assert_eq!(format_duration(Duration::from_secs(0)), "0s");
    }

    #[test]
    fn format_duration_exact_minute() {
        assert_eq!(format_duration(Duration::from_secs(60)), "1m 0s");
    }

    // ── capitalize ─────────────────────────────────────────────────

    #[test]
    fn capitalize_normal() {
        assert_eq!(capitalize("claude"), "Claude");
    }

    #[test]
    fn capitalize_empty() {
        assert_eq!(capitalize(""), "");
    }

    #[test]
    fn capitalize_already_upper() {
        assert_eq!(capitalize("Claude"), "Claude");
    }

    #[test]
    fn capitalize_single_char() {
        assert_eq!(capitalize("c"), "C");
    }

    #[test]
    fn capitalize_multibyte() {
        assert_eq!(capitalize("über"), "Über");
    }
}
